// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDawGPx6rTeAiQ0tEFCCPRMafVQTSEWTh0',
    appId: '1:66257255126:web:46b7d07229b02b7328e777',
    messagingSenderId: '66257255126',
    projectId: 'paperbot-rhxui0',
    authDomain: 'paperbot-rhxui0.firebaseapp.com',
    storageBucket: 'paperbot-rhxui0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpPKUJprxJXf35uGDWByMRb4K1lrmXjj4',
    appId: '1:66257255126:android:05121e4b2d273db328e777',
    messagingSenderId: '66257255126',
    projectId: 'paperbot-rhxui0',
    storageBucket: 'paperbot-rhxui0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJw-6WasBK8M4JAppOoX6_gJbga-D5iy0',
    appId: '1:66257255126:ios:b9acdc3cb042cd6528e777',
    messagingSenderId: '66257255126',
    projectId: 'paperbot-rhxui0',
    storageBucket: 'paperbot-rhxui0.appspot.com',
    androidClientId: '66257255126-6kk19k2l4eahd0t24di46e711id4ovpt.apps.googleusercontent.com',
    iosClientId: '66257255126-ff2o0j2rjo2met4tj2h7i71pdr78kf4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduflowFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJw-6WasBK8M4JAppOoX6_gJbga-D5iy0',
    appId: '1:66257255126:ios:b9acdc3cb042cd6528e777',
    messagingSenderId: '66257255126',
    projectId: 'paperbot-rhxui0',
    storageBucket: 'paperbot-rhxui0.appspot.com',
    androidClientId: '66257255126-6kk19k2l4eahd0t24di46e711id4ovpt.apps.googleusercontent.com',
    iosClientId: '66257255126-ff2o0j2rjo2met4tj2h7i71pdr78kf4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduflowFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1q6J0j-6SYi_PN5runEdrbOam98pQTw8',
    appId: '1:66257255126:web:29fdb429225eb66b28e777',
    messagingSenderId: '66257255126',
    projectId: 'paperbot-rhxui0',
    authDomain: 'paperbot-rhxui0.firebaseapp.com',
    storageBucket: 'paperbot-rhxui0.appspot.com',
  );
}
